name: Generate Snake Animation

on:
  schedule: # Executa o job diariamente
    - cron: "0 3 * * *" # A cada dia às 3h00 UTC
  workflow_dispatch: # Permite a execução manual do workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2.0.0
        with:
          github_user_name: Riscadin # Substitua pelo seu nome de usuário
          outputs: dist/snake.svg

      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
